name: Test
on:
  push:
    branches-ignore:
      - main

env:
  APP_NAME: typography
  STAGING_URL: asda.io37.ch

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Runs the tldr target
        run: make tldr

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: make a gitconfig
        run: |
          echo -e "[user]
          name = github-runner
          email = githubrunner@google.fi
          " > ~/.gitconfig

      - name: Installs the site
        run: npm_config_yes=true npx venlo@latest --appName venlo --language astro --design readme --colorScheme detective

      - name: Copies top readme to index
        run: cp README.md ${{ env.APP_NAME }}/src/content/top/index.md

      - name: Copies changelog to index
        run: cp CHANGELOG.md ${{ env.APP_NAME }}/src/content/top/changelog.md

      - name: Copies images to docsite
        run: cp images/*.png ${{ env.APP_NAME }}/public/images

      - name: Build docs site
        run: cd ${{ env.APP_NAME }} && make build

      - name: Create branch.html
        run: |
          cp .github/templates/branch.html ${{ env.APP_NAME }}/dist/branch.html
          cp .github/templates/workflow.css ${{ env.APP_NAME }}/dist/workflow.css
          sed -i 's|\[REPO_NAME\]|'"$GITHUB_REPOSITORY"'|g' ${{ env.APP_NAME }}/dist/branch.html
          sed -i 's|\[BRANCH_NAME\]|'"$(echo $GITHUB_REF | sed 's|refs/heads/||')"'|g' ${{ env.APP_NAME }}/dist/branch.html
          sed -i 's|\[DATE\]|'"$(date)"'|g' ${{ env.APP_NAME }}/dist/branch.html

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: ${{ env.APP_NAME }}/dist/
          remote_path: "/var/www/html/${{ env.STAGING_URL }}"
          remote_host: ${{ env.STAGING_URL }}
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
